/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Time = IDL.Int;
export const CheckIn = IDL.Record({
  'date' : Time,
  'notes' : IDL.Text,
  'location' : IDL.Text,
});
export const Status = IDL.Variant({
  'new' : IDL.Null,
  'enrolled' : IDL.Null,
  'lost' : IDL.Null,
  'contacted' : IDL.Null,
});
export const Record = IDL.Record({
  'status' : Status,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BlogPost = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'authorName' : IDL.Text,
  'publishedAt' : Time,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const FieldExecProfile = IDL.Record({
  'name' : IDL.Text,
  'leads' : IDL.Vec(Record),
  'checkIns' : IDL.Vec(CheckIn),
});
export const ExamResult = IDL.Record({
  'subject' : IDL.Text,
  'score' : IDL.Nat,
  'grade' : IDL.Text,
});
export const Status__1 = IDL.Variant({
  'present' : IDL.Null,
  'absent' : IDL.Null,
});
export const Record__1 = IDL.Record({ 'status' : Status__1, 'date' : Time });
export const TeacherId = IDL.Nat;
export const Certificate = IDL.Record({ 'title' : IDL.Text, 'date' : Time });
export const FieldExecId = IDL.Nat;
export const StudentProfile = IDL.Record({
  'name' : IDL.Text,
  'examResults' : IDL.Vec(ExamResult),
  'attendance' : IDL.Vec(Record__1),
  'gradeLevel' : IDL.Text,
  'teacherId' : TeacherId,
  'certificates' : IDL.Vec(Certificate),
  'fieldExecId' : FieldExecId,
});
export const ScheduleEntry = IDL.Record({
  'day' : IDL.Text,
  'subject' : IDL.Text,
  'time' : IDL.Text,
  'className' : IDL.Text,
});
export const TeacherProfile = IDL.Record({
  'subjects' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'schedule' : IDL.Vec(ScheduleEntry),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});
export const DemoBooking = IDL.Record({
  'name' : IDL.Text,
  'createdAt' : Time,
  'email' : IDL.Text,
  'grade' : IDL.Text,
  'preferredTime' : Time,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCheckIn' : IDL.Func([CheckIn], [], []),
  'addLead' : IDL.Func([Record], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createFieldExecProfile' : IDL.Func([IDL.Text], [], []),
  'createOrUpdateBlogPost' : IDL.Func([IDL.Opt(IDL.Nat), BlogPost], [], []),
  'createStudentProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createTeacherProfile' : IDL.Func([IDL.Text], [], []),
  'getAllFieldExecProfiles' : IDL.Func(
      [],
      [IDL.Vec(FieldExecProfile)],
      ['query'],
    ),
  'getAllStudentProfiles' : IDL.Func([], [IDL.Vec(StudentProfile)], ['query']),
  'getAllTeacherProfiles' : IDL.Func([], [IDL.Vec(TeacherProfile)], ['query']),
  'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getDemoBookings' : IDL.Func([], [IDL.Vec(DemoBooking)], ['query']),
  'getFieldExecProfile' : IDL.Func(
      [IDL.Principal],
      [FieldExecProfile],
      ['query'],
    ),
  'getStudentProfile' : IDL.Func([IDL.Principal], [StudentProfile], ['query']),
  'getTeacherProfile' : IDL.Func([IDL.Principal], [TeacherProfile], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markStudentAttendance' : IDL.Func([IDL.Principal, Time, Status__1], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContact' : IDL.Func([ContactSubmission], [], []),
  'submitDemoBooking' : IDL.Func([DemoBooking], [], []),
  'updateLead' : IDL.Func([IDL.Nat, Record], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Time = IDL.Int;
  const CheckIn = IDL.Record({
    'date' : Time,
    'notes' : IDL.Text,
    'location' : IDL.Text,
  });
  const Status = IDL.Variant({
    'new' : IDL.Null,
    'enrolled' : IDL.Null,
    'lost' : IDL.Null,
    'contacted' : IDL.Null,
  });
  const Record = IDL.Record({
    'status' : Status,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BlogPost = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'authorName' : IDL.Text,
    'publishedAt' : Time,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const FieldExecProfile = IDL.Record({
    'name' : IDL.Text,
    'leads' : IDL.Vec(Record),
    'checkIns' : IDL.Vec(CheckIn),
  });
  const ExamResult = IDL.Record({
    'subject' : IDL.Text,
    'score' : IDL.Nat,
    'grade' : IDL.Text,
  });
  const Status__1 = IDL.Variant({ 'present' : IDL.Null, 'absent' : IDL.Null });
  const Record__1 = IDL.Record({ 'status' : Status__1, 'date' : Time });
  const TeacherId = IDL.Nat;
  const Certificate = IDL.Record({ 'title' : IDL.Text, 'date' : Time });
  const FieldExecId = IDL.Nat;
  const StudentProfile = IDL.Record({
    'name' : IDL.Text,
    'examResults' : IDL.Vec(ExamResult),
    'attendance' : IDL.Vec(Record__1),
    'gradeLevel' : IDL.Text,
    'teacherId' : TeacherId,
    'certificates' : IDL.Vec(Certificate),
    'fieldExecId' : FieldExecId,
  });
  const ScheduleEntry = IDL.Record({
    'day' : IDL.Text,
    'subject' : IDL.Text,
    'time' : IDL.Text,
    'className' : IDL.Text,
  });
  const TeacherProfile = IDL.Record({
    'subjects' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'schedule' : IDL.Vec(ScheduleEntry),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  const DemoBooking = IDL.Record({
    'name' : IDL.Text,
    'createdAt' : Time,
    'email' : IDL.Text,
    'grade' : IDL.Text,
    'preferredTime' : Time,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCheckIn' : IDL.Func([CheckIn], [], []),
    'addLead' : IDL.Func([Record], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createFieldExecProfile' : IDL.Func([IDL.Text], [], []),
    'createOrUpdateBlogPost' : IDL.Func([IDL.Opt(IDL.Nat), BlogPost], [], []),
    'createStudentProfile' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createTeacherProfile' : IDL.Func([IDL.Text], [], []),
    'getAllFieldExecProfiles' : IDL.Func(
        [],
        [IDL.Vec(FieldExecProfile)],
        ['query'],
      ),
    'getAllStudentProfiles' : IDL.Func(
        [],
        [IDL.Vec(StudentProfile)],
        ['query'],
      ),
    'getAllTeacherProfiles' : IDL.Func(
        [],
        [IDL.Vec(TeacherProfile)],
        ['query'],
      ),
    'getBlogPosts' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getDemoBookings' : IDL.Func([], [IDL.Vec(DemoBooking)], ['query']),
    'getFieldExecProfile' : IDL.Func(
        [IDL.Principal],
        [FieldExecProfile],
        ['query'],
      ),
    'getStudentProfile' : IDL.Func(
        [IDL.Principal],
        [StudentProfile],
        ['query'],
      ),
    'getTeacherProfile' : IDL.Func(
        [IDL.Principal],
        [TeacherProfile],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markStudentAttendance' : IDL.Func(
        [IDL.Principal, Time, Status__1],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContact' : IDL.Func([ContactSubmission], [], []),
    'submitDemoBooking' : IDL.Func([DemoBooking], [], []),
    'updateLead' : IDL.Func([IDL.Nat, Record], [], []),
  });
};

export const init = ({ IDL }) => { return []; };