/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'title' : string,
  'content' : string,
  'authorName' : string,
  'publishedAt' : Time,
  'excerpt' : string,
  'category' : string,
}
export interface Certificate { 'title' : string, 'date' : Time }
export interface CheckIn {
  'date' : Time,
  'notes' : string,
  'location' : string,
}
export interface ContactSubmission {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'message' : string,
  'phone' : string,
}
export interface DemoBooking {
  'name' : string,
  'createdAt' : Time,
  'email' : string,
  'grade' : string,
  'preferredTime' : Time,
  'phone' : string,
}
export interface ExamResult {
  'subject' : string,
  'score' : bigint,
  'grade' : string,
}
export type FieldExecId = bigint;
export interface FieldExecProfile {
  'name' : string,
  'leads' : Array<Record>,
  'checkIns' : Array<CheckIn>,
}
export interface Record {
  'status' : Status,
  'name' : string,
  'notes' : string,
  'phone' : string,
}
export interface Record__1 { 'status' : Status__1, 'date' : Time }
export interface ScheduleEntry {
  'day' : string,
  'subject' : string,
  'time' : string,
  'className' : string,
}
export type Status = { 'new' : null } |
  { 'enrolled' : null } |
  { 'lost' : null } |
  { 'contacted' : null };
export type Status__1 = { 'present' : null } |
  { 'absent' : null };
export interface StudentProfile {
  'name' : string,
  'examResults' : Array<ExamResult>,
  'attendance' : Array<Record__1>,
  'gradeLevel' : string,
  'teacherId' : TeacherId,
  'certificates' : Array<Certificate>,
  'fieldExecId' : FieldExecId,
}
export type TeacherId = bigint;
export interface TeacherProfile {
  'subjects' : Array<string>,
  'name' : string,
  'schedule' : Array<ScheduleEntry>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCheckIn' : ActorMethod<[CheckIn], undefined>,
  'addLead' : ActorMethod<[Record], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createFieldExecProfile' : ActorMethod<[string], undefined>,
  'createOrUpdateBlogPost' : ActorMethod<[[] | [bigint], BlogPost], undefined>,
  'createStudentProfile' : ActorMethod<[string, string], undefined>,
  'createTeacherProfile' : ActorMethod<[string], undefined>,
  'getAllFieldExecProfiles' : ActorMethod<[], Array<FieldExecProfile>>,
  'getAllStudentProfiles' : ActorMethod<[], Array<StudentProfile>>,
  'getAllTeacherProfiles' : ActorMethod<[], Array<TeacherProfile>>,
  'getBlogPosts' : ActorMethod<[], Array<BlogPost>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getDemoBookings' : ActorMethod<[], Array<DemoBooking>>,
  'getFieldExecProfile' : ActorMethod<[Principal], FieldExecProfile>,
  'getStudentProfile' : ActorMethod<[Principal], StudentProfile>,
  'getTeacherProfile' : ActorMethod<[Principal], TeacherProfile>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markStudentAttendance' : ActorMethod<
    [Principal, Time, Status__1],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContact' : ActorMethod<[ContactSubmission], undefined>,
  'submitDemoBooking' : ActorMethod<[DemoBooking], undefined>,
  'updateLead' : ActorMethod<[bigint, Record], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];