/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface BlogPost {
    title: string;
    content: string;
    authorName: string;
    publishedAt: Time;
    excerpt: string;
    category: string;
}
export type Time = bigint;
export interface ContactSubmission {
    name: string;
    createdAt: Time;
    email: string;
    message: string;
    phone: string;
}
export interface ScheduleEntry {
    day: string;
    subject: string;
    time: string;
    className: string;
}
export interface FieldExecProfile {
    name: string;
    leads: Array<Record_>;
    checkIns: Array<CheckIn>;
}
export interface TeacherProfile {
    subjects: Array<string>;
    name: string;
    schedule: Array<ScheduleEntry>;
}
export type TeacherId = bigint;
export interface DemoBooking {
    name: string;
    createdAt: Time;
    email: string;
    grade: string;
    preferredTime: Time;
    phone: string;
}
export interface StudentProfile {
    name: string;
    examResults: Array<ExamResult>;
    attendance: Array<Record__1>;
    gradeLevel: string;
    teacherId: TeacherId;
    certificates: Array<Certificate>;
    fieldExecId: FieldExecId;
}
export interface CheckIn {
    date: Time;
    notes: string;
    location: string;
}
export interface Record_ {
    status: Status;
    name: string;
    notes: string;
    phone: string;
}
export interface Record__1 {
    status: Status__1;
    date: Time;
}
export interface ExamResult {
    subject: string;
    score: bigint;
    grade: string;
}
export type FieldExecId = bigint;
export interface UserProfile {
    name: string;
    role: string;
}
export interface Certificate {
    title: string;
    date: Time;
}
export enum Status {
    new_ = "new",
    enrolled = "enrolled",
    lost = "lost",
    contacted = "contacted"
}
export enum Status__1 {
    present = "present",
    absent = "absent"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCheckIn(checkIn: CheckIn): Promise<void>;
    addLead(lead: Record_): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createFieldExecProfile(name: string): Promise<void>;
    createOrUpdateBlogPost(id: bigint | null, post: BlogPost): Promise<void>;
    createStudentProfile(name: string, gradeLevel: string): Promise<void>;
    createTeacherProfile(name: string): Promise<void>;
    getAllFieldExecProfiles(): Promise<Array<FieldExecProfile>>;
    getAllStudentProfiles(): Promise<Array<StudentProfile>>;
    getAllTeacherProfiles(): Promise<Array<TeacherProfile>>;
    getBlogPosts(): Promise<Array<BlogPost>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getDemoBookings(): Promise<Array<DemoBooking>>;
    getFieldExecProfile(fieldExecPrincipal: Principal): Promise<FieldExecProfile>;
    getStudentProfile(studentPrincipal: Principal): Promise<StudentProfile>;
    getTeacherProfile(teacherPrincipal: Principal): Promise<TeacherProfile>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    markStudentAttendance(studentPrincipal: Principal, date: Time, status: Status__1): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitContact(contact: ContactSubmission): Promise<void>;
    submitDemoBooking(booking: DemoBooking): Promise<void>;
    updateLead(leadIndex: bigint, updatedLead: Record_): Promise<void>;
}
import type { Certificate as _Certificate, CheckIn as _CheckIn, ExamResult as _ExamResult, FieldExecId as _FieldExecId, FieldExecProfile as _FieldExecProfile, Record as _Record, Record__1 as _Record__1, Status as _Status, Status__1 as _Status__1, StudentProfile as _StudentProfile, TeacherId as _TeacherId, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCheckIn(arg0: CheckIn): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCheckIn(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCheckIn(arg0);
            return result;
        }
    }
    async addLead(arg0: Record_): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addLead(to_candid_Record_n1(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLead(to_candid_Record_n1(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createFieldExecProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createFieldExecProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createFieldExecProfile(arg0);
            return result;
        }
    }
    async createOrUpdateBlogPost(arg0: bigint | null, arg1: BlogPost): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateBlogPost(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateBlogPost(to_candid_opt_n7(this._uploadFile, this._downloadFile, arg0), arg1);
            return result;
        }
    }
    async createStudentProfile(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createStudentProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStudentProfile(arg0, arg1);
            return result;
        }
    }
    async createTeacherProfile(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createTeacherProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTeacherProfile(arg0);
            return result;
        }
    }
    async getAllFieldExecProfiles(): Promise<Array<FieldExecProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllFieldExecProfiles();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllFieldExecProfiles();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllStudentProfiles(): Promise<Array<StudentProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllStudentProfiles();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllStudentProfiles();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllTeacherProfiles(): Promise<Array<TeacherProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTeacherProfiles();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTeacherProfiles();
            return result;
        }
    }
    async getBlogPosts(): Promise<Array<BlogPost>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBlogPosts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBlogPosts();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getDemoBookings(): Promise<Array<DemoBooking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDemoBookings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDemoBookings();
            return result;
        }
    }
    async getFieldExecProfile(arg0: Principal): Promise<FieldExecProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getFieldExecProfile(arg0);
                return from_candid_FieldExecProfile_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFieldExecProfile(arg0);
            return from_candid_FieldExecProfile_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStudentProfile(arg0: Principal): Promise<StudentProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getStudentProfile(arg0);
                return from_candid_StudentProfile_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStudentProfile(arg0);
            return from_candid_StudentProfile_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTeacherProfile(arg0: Principal): Promise<TeacherProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getTeacherProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTeacherProfile(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async markStudentAttendance(arg0: Principal, arg1: Time, arg2: Status__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markStudentAttendance(arg0, arg1, to_candid_Status__1_n27(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markStudentAttendance(arg0, arg1, to_candid_Status__1_n27(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async submitContact(arg0: ContactSubmission): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContact(arg0);
            return result;
        }
    }
    async submitDemoBooking(arg0: DemoBooking): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDemoBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDemoBooking(arg0);
            return result;
        }
    }
    async updateLead(arg0: bigint, arg1: Record_): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLead(arg0, to_candid_Record_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLead(arg0, to_candid_Record_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_FieldExecProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldExecProfile): FieldExecProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Record__1_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Record__1): Record__1 {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_Record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Record): Record_ {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Status__1_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status__1): Status__1 {
    return from_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function from_candid_Status_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Status): Status {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_StudentProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StudentProfile): StudentProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    leads: Array<_Record>;
    checkIns: Array<_CheckIn>;
}): {
    name: string;
    leads: Array<Record_>;
    checkIns: Array<CheckIn>;
} {
    return {
        name: value.name,
        leads: from_candid_vec_n11(_uploadFile, _downloadFile, value.leads),
        checkIns: value.checkIns
    };
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status;
    name: string;
    notes: string;
    phone: string;
}): {
    status: Status;
    name: string;
    notes: string;
    phone: string;
} {
    return {
        status: from_candid_Status_n14(_uploadFile, _downloadFile, value.status),
        name: value.name,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    examResults: Array<_ExamResult>;
    attendance: Array<_Record__1>;
    gradeLevel: string;
    teacherId: _TeacherId;
    certificates: Array<_Certificate>;
    fieldExecId: _FieldExecId;
}): {
    name: string;
    examResults: Array<ExamResult>;
    attendance: Array<Record__1>;
    gradeLevel: string;
    teacherId: TeacherId;
    certificates: Array<Certificate>;
    fieldExecId: FieldExecId;
} {
    return {
        name: value.name,
        examResults: value.examResults,
        attendance: from_candid_vec_n19(_uploadFile, _downloadFile, value.attendance),
        gradeLevel: value.gradeLevel,
        teacherId: value.teacherId,
        certificates: value.certificates,
        fieldExecId: value.fieldExecId
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _Status__1;
    date: _Time;
}): {
    status: Status__1;
    date: Time;
} {
    return {
        status: from_candid_Status__1_n22(_uploadFile, _downloadFile, value.status),
        date: value.date
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    enrolled: null;
} | {
    lost: null;
} | {
    contacted: null;
}): Status {
    return "new" in value ? Status.new : "enrolled" in value ? Status.enrolled : "lost" in value ? Status.lost : "contacted" in value ? Status.contacted : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    present: null;
} | {
    absent: null;
}): Status__1 {
    return "present" in value ? Status__1.present : "absent" in value ? Status__1.absent : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Record>): Array<Record_> {
    return value.map((x)=>from_candid_Record_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StudentProfile>): Array<StudentProfile> {
    return value.map((x)=>from_candid_StudentProfile_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Record__1>): Array<Record__1> {
    return value.map((x)=>from_candid_Record__1_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FieldExecProfile>): Array<FieldExecProfile> {
    return value.map((x)=>from_candid_FieldExecProfile_n9(_uploadFile, _downloadFile, x));
}
function to_candid_Record_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Record_): _Record {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Status__1_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): _Status__1 {
    return to_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function to_candid_Status_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): _Status {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Status;
    name: string;
    notes: string;
    phone: string;
}): {
    status: _Status;
    name: string;
    notes: string;
    phone: string;
} {
    return {
        status: to_candid_Status_n3(_uploadFile, _downloadFile, value.status),
        name: value.name,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status__1): {
    present: null;
} | {
    absent: null;
} {
    return value == Status__1.present ? {
        present: null
    } : value == Status__1.absent ? {
        absent: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Status): {
    new: null;
} | {
    enrolled: null;
} | {
    lost: null;
} | {
    contacted: null;
} {
    return value == Status.new ? {
        new_: null
    } : value == Status.enrolled ? {
        enrolled: null
    } : value == Status.lost ? {
        lost: null
    } : value == Status.contacted ? {
        contacted: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
